import React, { useState } from 'react';
import { 
  Settings as SettingsIcon,
  Key,
  Bell,
  Palette,
  Globe,
  Shield,
  Database,
  Cloud,
  Terminal,
  Save,
  Check,
  AlertCircle,
  Eye,
  EyeOff,
  RefreshCw,
  Download,
  Upload,
  Trash2,
  Info
} from 'lucide-react';
import { motion } from 'framer-motion';

const Settings = () => {
  const [activeTab, setActiveTab] = useState('api');
  const [showApiKey, setShowApiKey] = useState(false);
  const [saved, setSaved] = useState(false);
  const [settings, setSettings] = useState({
    // API Settings
    geminiApiKey: '',
    emergentApiKey: '',
    openaiApiKey: '',
    anthropicApiKey: '',
    
    // Notification Settings
    emailNotifications: true,
    pushNotifications: false,
    slackWebhook: '',
    notifyOnComplete: true,
    notifyOnError: true,
    
    // Appearance
    theme: 'dark',
    accentColor: 'purple',
    compactMode: false,
    
    // Generation Settings
    defaultPlatform: 'web',
    defaultArchitecture: 'modular',
    autoGenerateTests: true,
    autoGenerateDocs: true,
    enableCodeReview: true,
    
    // Export Settings
    includeDockerfiles: true,
    includeGithubActions: true,
    includeReadme: true,
    compressionLevel: 'normal',
    
    // Advanced
    debugMode: false,
    verboseLogs: false,
    maxConcurrentAgents: 4,
    generationTimeout: 300
  });

  const handleSave = () => {
    // Save settings to localStorage or backend
    localStorage.setItem('agentGenSettings', JSON.stringify(settings));
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  const handleReset = () => {
    if (window.confirm('Are you sure you want to reset all settings to defaults?')) {
      setSettings({
        geminiApiKey: '',
        emergentApiKey: '',
        openaiApiKey: '',
        anthropicApiKey: '',
        emailNotifications: true,
        pushNotifications: false,
        slackWebhook: '',
        notifyOnComplete: true,
        notifyOnError: true,
        theme: 'dark',
        accentColor: 'purple',
        compactMode: false,
        defaultPlatform: 'web',
        defaultArchitecture: 'modular',
        autoGenerateTests: true,
        autoGenerateDocs: true,
        enableCodeReview: true,
        includeDockerfiles: true,
        includeGithubActions: true,
        includeReadme: true,
        compressionLevel: 'normal',
        debugMode: false,
        verboseLogs: false,
        maxConcurrentAgents: 4,
        generationTimeout: 300
      });
    }
  };

  const tabs = [
    { id: 'api', name: 'API Keys', icon: Key },
    { id: 'notifications', name: 'Notifications', icon: Bell },
    { id: 'appearance', name: 'Appearance', icon: Palette },
    { id: 'generation', name: 'Generation', icon: Terminal },
    { id: 'export', name: 'Export', icon: Download },
    { id: 'advanced', name: 'Advanced', icon: SettingsIcon }
  ];

  const ToggleSwitch = ({ enabled, onChange }) => (
    <button
      onClick={() => onChange(!enabled)}
      className={`relative w-12 h-6 rounded-full transition-colors ${
        enabled ? 'bg-purple-500' : 'bg-gray-600'
      }`}
    >
      <span
        className={`absolute top-1 w-4 h-4 bg-white rounded-full transition-transform ${
          enabled ? 'left-7' : 'left-1'
        }`}
      />
    </button>
  );

  const InputField = ({ label, value, onChange, type = 'text', placeholder, isSecret = false, info }) => {
    const [showSecret, setShowSecret] = useState(false);
    
    return (
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <label className="text-gray-300 text-sm font-medium">{label}</label>
          {info && (
            <div className="group relative">
              <Info className="w-4 h-4 text-gray-500 cursor-help" />
              <div className="absolute right-0 bottom-6 hidden group-hover:block w-64 p-2 bg-gray-700 rounded-lg text-xs text-gray-300 z-10">
                {info}
              </div>
            </div>
          )}
        </div>
        <div className="relative">
          <input
            type={isSecret && !showSecret ? 'password' : type}
            value={value}
            onChange={(e) => onChange(e.target.value)}
            placeholder={placeholder}
            className="w-full px-4 py-3 bg-gray-700/50 border border-purple-500/20 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-purple-500"
          />
          {isSecret && (
            <button
              onClick={() => setShowSecret(!showSecret)}
              className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-white"
            >
              {showSecret ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
            </button>
          )}
        </div>
      </div>
    );
  };

  const SelectField = ({ label, value, onChange, options }) => (
    <div className="space-y-2">
      <label className="text-gray-300 text-sm font-medium">{label}</label>
      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="w-full px-4 py-3 bg-gray-700/50 border border-purple-500/20 rounded-lg text-white focus:outline-none focus:border-purple-500"
      >
        {options.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
    </div>
  );

  const renderTabContent = () => {
    switch (activeTab) {
      case 'api':
        return (
          <div className="space-y-6">
            <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4 flex items-start space-x-3">
              <AlertCircle className="w-5 h-5 text-blue-400 mt-0.5" />
              <div>
                <p className="text-blue-300 font-medium">API Keys are stored locally</p>
                <p className="text-blue-200/70 text-sm">Your API keys are encrypted and stored in your browser. They are never sent to our servers.</p>
              </div>
            </div>
            
            <InputField
              label="Emergent LLM Key"
              value={settings.emergentApiKey}
              onChange={(v) => setSettings({...settings, emergentApiKey: v})}
              placeholder="ek-..."
              isSecret={true}
              info="Universal key for OpenAI, Anthropic, and Google models through Emergent"
            />
            
            <InputField
              label="Gemini API Key"
              value={settings.geminiApiKey}
              onChange={(v) => setSettings({...settings, geminiApiKey: v})}
              placeholder="AIza..."
              isSecret={true}
              info="Get your key from Google AI Studio"
            />
            
            <InputField
              label="OpenAI API Key (Optional)"
              value={settings.openaiApiKey}
              onChange={(v) => setSettings({...settings, openaiApiKey: v})}
              placeholder="sk-..."
              isSecret={true}
              info="Direct OpenAI API access (not needed if using Emergent key)"
            />
            
            <InputField
              label="Anthropic API Key (Optional)"
              value={settings.anthropicApiKey}
              onChange={(v) => setSettings({...settings, anthropicApiKey: v})}
              placeholder="sk-ant-..."
              isSecret={true}
              info="Direct Anthropic API access (not needed if using Emergent key)"
            />
          </div>
        );
        
      case 'notifications':
        return (
          <div className="space-y-6">
            <div className="flex items-center justify-between py-4 border-b border-gray-700/50">
              <div>
                <h3 className="text-white font-medium">Email Notifications</h3>
                <p className="text-gray-400 text-sm">Receive updates via email</p>
              </div>
              <ToggleSwitch
                enabled={settings.emailNotifications}
                onChange={(v) => setSettings({...settings, emailNotifications: v})}
              />
            </div>
            
            <div className="flex items-center justify-between py-4 border-b border-gray-700/50">
              <div>
                <h3 className="text-white font-medium">Push Notifications</h3>
                <p className="text-gray-400 text-sm">Browser push notifications</p>
              </div>
              <ToggleSwitch
                enabled={settings.pushNotifications}
                onChange={(v) => setSettings({...settings, pushNotifications: v})}
              />
            </div>
            
            <div className="flex items-center justify-between py-4 border-b border-gray-700/50">
              <div>
                <h3 className="text-white font-medium">Notify on Completion</h3>
                <p className="text-gray-400 text-sm">Alert when generation completes</p>
              </div>
              <ToggleSwitch
                enabled={settings.notifyOnComplete}
                onChange={(v) => setSettings({...settings, notifyOnComplete: v})}
              />
            </div>
            
            <div className="flex items-center justify-between py-4 border-b border-gray-700/50">
              <div>
                <h3 className="text-white font-medium">Notify on Error</h3>
                <p className="text-gray-400 text-sm">Alert when generation fails</p>
              </div>
              <ToggleSwitch
                enabled={settings.notifyOnError}
                onChange={(v) => setSettings({...settings, notifyOnError: v})}
              />
            </div>
            
            <InputField
              label="Slack Webhook URL (Optional)"
              value={settings.slackWebhook}
              onChange={(v) => setSettings({...settings, slackWebhook: v})}
              placeholder="https://hooks.slack.com/services/..."
              info="Send notifications to a Slack channel"
            />
          </div>
        );
        
      case 'appearance':
        return (
          <div className="space-y-6">
            <SelectField
              label="Theme"
              value={settings.theme}
              onChange={(v) => setSettings({...settings, theme: v})}
              options={[
                { value: 'dark', label: 'Dark Mode' },
                { value: 'light', label: 'Light Mode' },
                { value: 'system', label: 'System Default' }
              ]}
            />
            
            <div className="space-y-2">
              <label className="text-gray-300 text-sm font-medium">Accent Color</label>
              <div className="flex space-x-3">
                {['purple', 'blue', 'green', 'pink', 'orange'].map((color) => (
                  <button
                    key={color}
                    onClick={() => setSettings({...settings, accentColor: color})}
                    className={`w-10 h-10 rounded-lg ${
                      color === 'purple' ? 'bg-purple-500' :
                      color === 'blue' ? 'bg-blue-500' :
                      color === 'green' ? 'bg-green-500' :
                      color === 'pink' ? 'bg-pink-500' :
                      'bg-orange-500'
                    } ${settings.accentColor === color ? 'ring-2 ring-white ring-offset-2 ring-offset-gray-900' : ''}`}
                  />
                ))}
              </div>
            </div>
            
            <div className="flex items-center justify-between py-4 border-b border-gray-700/50">
              <div>
                <h3 className="text-white font-medium">Compact Mode</h3>
                <p className="text-gray-400 text-sm">Reduce spacing and padding</p>
              </div>
              <ToggleSwitch
                enabled={settings.compactMode}
                onChange={(v) => setSettings({...settings, compactMode: v})}
              />
            </div>
          </div>
        );
        
      case 'generation':
        return (
          <div className="space-y-6">
            <SelectField
              label="Default Platform"
              value={settings.defaultPlatform}
              onChange={(v) => setSettings({...settings, defaultPlatform: v})}
              options={[
                { value: 'web', label: 'Web Application' },
                { value: 'mobile', label: 'Mobile App' },
                { value: 'desktop', label: 'Desktop App' },
                { value: 'all', label: 'All Platforms' }
              ]}
            />
            
            <SelectField
              label="Default Architecture"
              value={settings.defaultArchitecture}
              onChange={(v) => setSettings({...settings, defaultArchitecture: v})}
              options={[
                { value: 'simple', label: 'Simple (Single File)' },
                { value: 'modular', label: 'Modular (Recommended)' },
                { value: 'microservices', label: 'Microservices' }
              ]}
            />
            
            <div className="flex items-center justify-between py-4 border-b border-gray-700/50">
              <div>
                <h3 className="text-white font-medium">Auto-Generate Tests</h3>
                <p className="text-gray-400 text-sm">Include unit and integration tests</p>
              </div>
              <ToggleSwitch
                enabled={settings.autoGenerateTests}
                onChange={(v) => setSettings({...settings, autoGenerateTests: v})}
              />
            </div>
            
            <div className="flex items-center justify-between py-4 border-b border-gray-700/50">
              <div>
                <h3 className="text-white font-medium">Auto-Generate Documentation</h3>
                <p className="text-gray-400 text-sm">Include README and API docs</p>
              </div>
              <ToggleSwitch
                enabled={settings.autoGenerateDocs}
                onChange={(v) => setSettings({...settings, autoGenerateDocs: v})}
              />
            </div>
            
            <div className="flex items-center justify-between py-4 border-b border-gray-700/50">
              <div>
                <h3 className="text-white font-medium">Enable Code Review</h3>
                <p className="text-gray-400 text-sm">Run code review agent on output</p>
              </div>
              <ToggleSwitch
                enabled={settings.enableCodeReview}
                onChange={(v) => setSettings({...settings, enableCodeReview: v})}
              />
            </div>
          </div>
        );
        
      case 'export':
        return (
          <div className="space-y-6">
            <div className="flex items-center justify-between py-4 border-b border-gray-700/50">
              <div>
                <h3 className="text-white font-medium">Include Dockerfiles</h3>
                <p className="text-gray-400 text-sm">Add Docker configuration files</p>
              </div>
              <ToggleSwitch
                enabled={settings.includeDockerfiles}
                onChange={(v) => setSettings({...settings, includeDockerfiles: v})}
              />
            </div>
            
            <div className="flex items-center justify-between py-4 border-b border-gray-700/50">
              <div>
                <h3 className="text-white font-medium">Include GitHub Actions</h3>
                <p className="text-gray-400 text-sm">Add CI/CD workflow files</p>
              </div>
              <ToggleSwitch
                enabled={settings.includeGithubActions}
                onChange={(v) => setSettings({...settings, includeGithubActions: v})}
              />
            </div>
            
            <div className="flex items-center justify-between py-4 border-b border-gray-700/50">
              <div>
                <h3 className="text-white font-medium">Include README</h3>
                <p className="text-gray-400 text-sm">Generate documentation</p>
              </div>
              <ToggleSwitch
                enabled={settings.includeReadme}
                onChange={(v) => setSettings({...settings, includeReadme: v})}
              />
            </div>
            
            <SelectField
              label="Compression Level"
              value={settings.compressionLevel}
              onChange={(v) => setSettings({...settings, compressionLevel: v})}
              options={[
                { value: 'none', label: 'No Compression' },
                { value: 'normal', label: 'Normal' },
                { value: 'maximum', label: 'Maximum' }
              ]}
            />
          </div>
        );
        
      case 'advanced':
        return (
          <div className="space-y-6">
            <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-4 flex items-start space-x-3">
              <AlertCircle className="w-5 h-5 text-yellow-400 mt-0.5" />
              <div>
                <p className="text-yellow-300 font-medium">Advanced Settings</p>
                <p className="text-yellow-200/70 text-sm">These settings are for advanced users. Modify with caution.</p>
              </div>
            </div>
            
            <div className="flex items-center justify-between py-4 border-b border-gray-700/50">
              <div>
                <h3 className="text-white font-medium">Debug Mode</h3>
                <p className="text-gray-400 text-sm">Enable detailed logging</p>
              </div>
              <ToggleSwitch
                enabled={settings.debugMode}
                onChange={(v) => setSettings({...settings, debugMode: v})}
              />
            </div>
            
            <div className="flex items-center justify-between py-4 border-b border-gray-700/50">
              <div>
                <h3 className="text-white font-medium">Verbose Logs</h3>
                <p className="text-gray-400 text-sm">Show all agent communications</p>
              </div>
              <ToggleSwitch
                enabled={settings.verboseLogs}
                onChange={(v) => setSettings({...settings, verboseLogs: v})}
              />
            </div>
            
            <InputField
              label="Max Concurrent Agents"
              value={settings.maxConcurrentAgents}
              onChange={(v) => setSettings({...settings, maxConcurrentAgents: parseInt(v) || 4})}
              type="number"
              info="Number of agents that can run simultaneously"
            />
            
            <InputField
              label="Generation Timeout (seconds)"
              value={settings.generationTimeout}
              onChange={(v) => setSettings({...settings, generationTimeout: parseInt(v) || 300})}
              type="number"
              info="Maximum time for code generation"
            />
            
            <div className="pt-4 border-t border-gray-700/50">
              <button
                onClick={handleReset}
                className="flex items-center space-x-2 px-4 py-2 bg-red-500/20 border border-red-500/30 rounded-lg text-red-400 hover:bg-red-500/30 transition-all"
              >
                <Trash2 className="w-4 h-4" />
                <span>Reset All Settings</span>
              </button>
            </div>
          </div>
        );
        
      default:
        return null;
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900/20 to-gray-900 py-8 px-4">
      <div className="max-w-5xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-white mb-2">Settings</h1>
          <p className="text-gray-400">Configure your application preferences</p>
        </div>

        <div className="grid grid-cols-12 gap-6">
          {/* Sidebar */}
          <div className="col-span-12 md:col-span-3">
            <div className="bg-gray-800/50 backdrop-blur-lg border border-purple-500/20 rounded-xl p-2">
              {tabs.map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`w-full flex items-center space-x-3 px-4 py-3 rounded-lg transition-all ${
                    activeTab === tab.id
                      ? 'bg-purple-500/20 text-purple-300'
                      : 'text-gray-400 hover:text-white hover:bg-white/5'
                  }`}
                >
                  <tab.icon className="w-5 h-5" />
                  <span>{tab.name}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Content */}
          <div className="col-span-12 md:col-span-9">
            <motion.div
              key={activeTab}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-gray-800/50 backdrop-blur-lg border border-purple-500/20 rounded-xl p-6"
            >
              {renderTabContent()}
            </motion.div>

            {/* Save Button */}
            <div className="mt-6 flex justify-end">
              <button
                onClick={handleSave}
                className={`flex items-center space-x-2 px-6 py-3 rounded-lg font-medium transition-all ${
                  saved
                    ? 'bg-green-500 text-white'
                    : 'bg-gradient-to-r from-purple-500 to-pink-500 text-white hover:opacity-90'
                }`}
              >
                {saved ? (
                  <>
                    <Check className="w-5 h-5" />
                    <span>Saved!</span>
                  </>
                ) : (
                  <>
                    <Save className="w-5 h-5" />
                    <span>Save Settings</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Settings;
